apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "lms.fullname" . }}
  labels:
  {{- include "lms.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
  - name: http
    containerPort:  {{ .Values.service.httpPort }}
    protocol: TCP
    targetPort: http
  - name: dlna
    containerPort:  {{ .Values.service.dlnaPort }}
    protocol: TCP
    targetPort: dlna
  - name: control
    containerPort:  {{ .Values.service.controlPort }}
    protocol: TCP
    targetPort: control
  - name: discovery
    containerPort:  {{ .Values.service.discoveryPort }}
    protocol: UDP
    targetPort: discovery
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    targetPort: metrics

  selector:
  {{- include "lms.selectorLabels" . | nindent 4 }}

