apiVersion: v1
kind: Service
metadata:
{{- if .Values.service.annotations }}
  annotations:
{{- toYaml .Values.service.annotations | nindent 4 }}
{{- end }}
  name: {{ include "lms.fullname" . }}
  labels:
{{- include "lms.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
{{- if .Values.service.externalIPs }}
  externalIPs:
{{- toYaml .Values.service.externalIPs | nindent 4 }}
{{- end }}
{{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
{{- end }}
{{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
{{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
  ports:
    - name: http
      protocol: TCP
      port: {{ .Values.service.http }}
      targetPort: http
    - name: dlna
      protocol: TCP
      port: {{ .Values.service.dlna }}
      targetPort: dlna
    - name: control
      protocol: TCP
      port: {{ .Values.service.control }}
      targetPort: control
    - name: discovery
      protocol: UDP
      port: {{ .Values.service.control }}
      targetPort: discovery
  selector:
{{- include "lms.selectorLabels" . | nindent 4 }}

