{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "zigbee2mqtt.fullname" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
spec:
  ingressClassName: {{ $.Values.ingressClassName }}
  rules:
    - host: {{ include "zigbee2mqtt.fullname" . }}.{{ $.Values.ingress.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "zigbee2mqtt.fullname" . }}
                port:
                  name: http
  tls:
    - secretName: cluster-tls
      hosts:
        - {{ include "zigbee2mqtt.fullname" . }}.{{ $.Values.ingress.domainName }}
{{- end }}
