apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "zigbee2mqtt.serviceAccountName" . }}
  labels:
    {{- include "zigbee2mqtt.labels" . | nindent 4 }}
  annotations:
    {{- toYaml . | nindent 4 }}
