apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}-config
  labels:
{{ include "eclipse-mosquitto.labels" . | indent 4 }}
data:
  mosquitto.conf: |
{{- with .Values.config }}
    {{- toYaml . | nindent 4 }}
{{- end }}