apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "eclipse-mosquitto.fullname" . }}
  labels:
  {{ include "eclipse-mosquitto.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit:  {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "eclipse-mosquitto.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  strategy:
    type: {{ .Values.strategyType }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "eclipse-mosquitto.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      serviceAccountName: {{ include "eclipse-mosquitto.serviceAccountName" . }}
    {{- if .Values.securityContext.enabled }}
      securityContext:
        fsGroup: {{ .Values.securityContext.fsGroup }}
        runAsUser: {{ .Values.securityContext.runAsUser }}
    {{- end }}
      initContainers:
      - name: init-config
        image: busybox
        command: ["/bin/cp", "-v", "/tmp/password_file", "/mosquitto/password_file"]
        securityContext:
          runAsNonRoot: false
          privileged: true
        volumeMounts:
        - name:      mosquitto-passwd
          mountPath: /tmp/password_file
          subPath:   password_file
        - name:      mosquitto-data
          mountPath: /mosquitto

      - name: setup-permissions
        image: busybox
        command: ["/bin/chown", "-R", "1883:1883", "/mosquitto"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name:      mosquitto-data
          mountPath: /mosquitto
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "mosquitto", "-c", "/mosquitto/config/mosquitto.conf"; "mosquitto", "-c", "/mosquitto/password_file" ]
        ports:
          - name: {{ .Values.container.ports.mqtt.name }}
            containerPort: {{ .Values.container.ports.mqtt.port }}
            protocol: TCP
          - name: {{ .Values.container.ports.mqtts.name }}
            containerPort: {{ .Values.container.ports.mqtts.port }}
            protocol: TCP
        livenessProbe:
          tcpSocket:
            port: {{ .Values.container.ports.mqtt.port }}
          initialDelaySeconds: 5
          periodSeconds: 15
        readinessProbe:
          tcpSocket:
            port: {{ .Values.container.ports.mqtt.port }}
          initialDelaySeconds: 5
          periodSeconds: 10
        volumeMounts:
          - name: mosquitto-conf
            mountPath: /mosquitto/config/mosquitto.conf
            subPath: mosquitto.conf
          - name: mosquitto-passwd
            mountPath: /mosquitto/password_file
            subPath: password_file
          - name: mosquitto-ca-cert
            mountPath: /mosquitto/config/certs/ca.crt
            subPath: ca.crt
          - name: mosquitto-server-cert
            mountPath: /mosquitto/config/certs/server.crt
            subPath: server.crt
          - name: mosquitto-server-key
            mountPath: /mosquitto/config/certs/server.key
            subPath: server.key
            readOnly: true
          - name: mosquitto-data
            mountPath: /mosquitto
            subPath: mosquitto
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: mosquitto-passwd
        secret:
          secretName: mosquitto-secrets
          items:
          - key:  password_file
            path: password_file
            mode: 0644
      - name: mosquitto-conf
        configMap:
          name: {{ include "eclipse-mosquitto.fullname" . }}-config
      - name: mosquitto-ca-cert
        secret:
          secretName: mosquitto-ca-cert
      - name: mosquitto-server-cert
        secret:
          secretName: mosquitto-server-cert
      - name: mosquitto-server-key
        secret:
          secretName: mosquitto-server-key
      - name: mosquitto-data
      {{- if .Values.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ include "eclipse-mosquitto.fullname" . }}-pvc
      {{- else }}
        emptyDir: {}
      {{- end -}}
    {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
