image:
  repository: lmscommunity/logitechmediaserver
  tag: 8.4.0
  pullPolicy: IfNotPresent

extraLabels: {}

settings:

service:
  annotations: {}
  clusterIP: ""
  httpPort: "9000"
  controlPort: "3483"
  externalIPs: []

  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP

ingress:
  enabled: false
  class:
  annotations: {}
  path: /
  hosts:
    - lms
  tls: []
  #  - secretName: lms-tls
  #    hosts:
  #      lms

persistence:
  enabled: true
  config:
    hostPath: /mnt/volume-0/apps/lms
  music:
    hostPath: /mnt/volume-0/media/music

# resources:
#   requests:
#     cpu: "1"
#     memory: "256Mi"
#   limits:
#     cpu: "1"
#     memory: "512Mi"

nodeSelector: {}

tolerations: []

affinity: {}
