image:
  repository: lmscommunity/logitechmediaserver
  tag: 8.4.0
  pullPolicy: IfNotPresent

strategyType: Recreate
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations: {}
  name: ""

podAnnotations: {}
podLabels:
  {}
podEnv:
  {}
#   - name: "exemple"
#     value: "3001"

podSecurityContext: {}
  # fsGroup: 2000
# dnsPolicy: ""
# dnsConfig: {}
securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  annotations: {}
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  httpPort: "9000"
  dlnaPort: "9090"
  controlPort: "3483"

ingress:
  enabled: false
  # className: ""
  annotations:
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    nginx.ingress.kubernetes.io/server-snippets: |
      location / {
        proxy_set_header Upgrade $http_upgrade;
        proxy_http_version 1.1;
        proxy_set_header X-Forwarded-Host $http_host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header Host $host;
        proxy_set_header Connection "upgrade";
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header   Upgrade $http_upgrade;
        proxy_cache_bypass $http_upgrade;
      }
  hosts:
    - host: lms.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
    []
    # - secretName: letsencrypt-staging
    #   hosts:
    #     - lms.local

# resources:
#   requests:
#     cpu: "1"
#     memory: "256Mi"
#   limits:
#     cpu: "1"
#     memory: "512Mi"

livenessProbe:
  enabled: true
  periodSeconds:       60
  timeoutSeconds:      10
  successThreshold:    1
  failureThreshold:    6
  initialDelaySeconds: 30
readinessProbe:
  enabled: true
  periodSeconds:       60
  timeoutSeconds:      10
  successThreshold:    1
  failureThreshold:    6
  initialDelaySeconds: 30

nodeSelector:
  kubernetes.io/hostname: {}
affinity: {}
tolerations: []

persistence:
  enabled: false
  configstorage:
    hostPath: /mnt/volume-0/apps/lms
  musicstorage:
    hostPath: /mnt/volume-0/media/music
  pvc:
    enabled: false
    # accessModes:
    #   - {}
    # resources:
    #   requests:
    #     storage: 2Gi
    # storageClassName: ""

serviceMonitor:
  enabled: true
  interval: 60s
  scrapeTimeout: 10s
  scheme: ~
  tlsConfig: {}
  relabelings: []
  metricRelabelings: []
  selector: {}
  namespace: ~
  additionalLabels: {}
  annotations: {}
