{{- if not .Values.useDeploy -}}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "uptime-kuma.fullname" . }}
  labels:
    {{- include "uptime-kuma.labels" . | nindent 4 }}

spec:
  serviceName: {{ include "uptime-kuma.fullname" . }}
  replicas: 1
  selector:
    matchLabels:
      {{- include "uptime-kuma.selectorLabels" . | nindent 6 }}
      {{- if .Values.podLabels }}
        {{- toYaml .Values.podLabels | nindent 6 }}
      {{- end }}

  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

      labels:
        {{- include "uptime-kuma.selectorLabels" . | nindent 8 }}
        {{- if .Values.podLabels }}
          {{- toYaml .Values.podLabels | nindent 8 }}
        {{- end }}

    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      enableServiceLinks: false
      serviceAccountName: {{ include "uptime-kuma.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- if .Values.dnsPolicy }}
      dnsPolicy: {{ .Values.dnsPolicy }}
      {{- end }}
      {{- if .Values.dnsConfig }}
      dnsConfig:
        {{- toYaml .Values.dnsConfig | nindent 8 }}
      {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{- with .Values.podEnv }}
        env:
          {{- toYaml . | nindent 12 }}
        {{- end }}

        ports:
        - name: http
          containerPort: 3001
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

        volumeMounts:
        - mountPath: /app/data
          name: uptime-kuma-storage

        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          exec:
            command:
              - extra/healthcheck
          timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds}}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
        {{- end }}

        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          httpGet:
            path: /
            port: 3001
            scheme: HTTP
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
        {{- end }}
        resources:
          {{- toYaml .Values.resources | nindent 12 }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}


      volumes:
      {{- if not .Values.persistence.enabled }}
      - name: uptime-kuma-storage
        hostPath:
          path: {{ .Values.persistence.hostPath }}
      {{- end }}
      
      # {{- if and .Values.persistence.enabled .Values.persistence.existingClaim }}
      # - name: uptime-kuma-storage
      #   persistentVolumeClaim:
      #     claimName: {{ .Values.persistence.existingClaim }}
      # {{- end }}
{{- end -}}