image:
  repository: eclipse-mosquitto
  tag: ""
  pullPolicy: IfNotPresent
nameOverride: ""
fullnameOverride: ""
revisionHistoryLimit: 2
replicas: 1
strategyType: RollingUpdate
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount:
  create: true
  annotations: {}
  automountServiceAccountToken: false
podAnnotations: {}

podSecurityContext:
  runAsUser: 1883
  runAsGroup: 1883
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  capabilities:
    drop:
    - ALL

securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

container:
  ports:
    mqtt:
      name: mqtt
      port: 1883
    mqtts:
      name: mqtts
      port: 8883

service:
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""
  externalTrafficPolicy: {}
  loadBalancerSourceRanges: []
  publishNotReadyAddresses: false
  ports:
    mqtt:
      name: mqtt
      port: 1883
    mqtts:
      name: mqtts
      port: 8883

nodeSelector:
  kubernetes.io/hostname: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 2Gi
  annotations: {}

