replicaCount: 1
revisionHistoryLimit: 2

image:
  repository: eclipse-mosquitto
  tag: ""
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 1883
  runAsGroup: 1883
  runAsNonRoot: true
  readOnlyRootFilesystem: false
  capabilities:
    drop:
    - ALL

securityContext:
  runAsUser: 999
  runAsGroup: 999
  fsGroup: 999

container:
  ports:
    mqtt:
      name: mqtt
      port: 1883
    mqtts:
      name: mqtts
      port: 8883

service:
  type: ClusterIP
  externalIPs: []
  loadBalancerIP: ""
  externalTrafficPolicy: {}
  loadBalancerSourceRanges: []
  publishNotReadyAddresses: false
  ports:
    mqtt:
      name: mqtt
      port: 1883
    mqtts:
      name: mqtts
      port: 8883

nodeSelector:
  kubernetes.io/hostname: {}

tolerations: []

affinity: {}

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  hosts:
    - host: chart-example.local
      paths: []

persistence:
  enabled: true
  storageClass: local-path
  accessMode: ReadWriteOnce
  size: 2Gi
  annotations: {}

# config:
#   allow_anonymous true
#   persistence true
#   persistence_location /mosquitto/data/
#   log_dest stdout
#   listener 1883
#   protocol mqtt
#   listener 8883
#   cafile /mosquitto/config/certs/ca.crt
#   certfile /mosquitto/config/certs/server.crt
#   keyfile /mosquitto/config/certs/server.key
#   require_certificate false

# certs:
#   ca:
#     crt: |-
#       -----BEGIN CERTIFICATE-----
#       -----END CERTIFICATE-----
#   server:
#     crt: |-
#       -----BEGIN CERTIFICATE-----
#       -----END CERTIFICATE-----
#     key: |-
#       -----BEGIN CERTIFICATE-----
#       -----END CERTIFICATE-----
