apiVersion: v2
appVersion: 0.14.0
description: ExternalDNS synchronizes exposed Kubernetes Services and Ingresses with DNS providers.
name: external-dns
version: 0.0.1
type: application
keywords:
  - kubernetes
  - externaldns
  - external-dns
  - dns
  - service
  - ingress
home: https://github.com/JacekZubielik/helm-charts/tree/master/charts/external-dns
icon: https://github.com/kubernetes-sigs/external-dns/raw/master/docs/img/external-dns.png
sources:
- https://github.com/kubernetes-sigs/external-dns/
maintainers:
- name: Jacek Zubielik
  email: jack.zu@protonmail.com

