apiVersion: v1
appVersion: RELEASE.2024-03-03T17-50-39Z
description: High Performance Object Storage
name: minio
version: 0.0.3
keywords:
- minio
- storage
- object-storage
- s3
- cluster
home: https://github.com/JacekZubielik/helm-charts/tree/master/charts/minio
icon: https://min.io/resources/img/logo/MINIO_wordmark.png
sources:
- https://github.com/minio/minio
maintainers:
- name: Jacek Zubielik
  email: jack.zu@protonmail.com
