


image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: 1.33.2

env:
  ZIGBEE2MQTT_DATA: /data
  TZ: Europe/Warsaw

service:
  main:
    enabled: true
    primary: true
    nameOverride:
    type: ClusterIP
    externalTrafficPolicy:
    ipFamilyPolicy:
    ipFamilies: []
    annotations: {}
    labels: {}
    ports:
      http:
        enabled: true
        primary: true
        port: 8080
        protocol: HTTP
        targetPort:
        nodePort:

ingress:
  main:
    enabled: true
    primary: true
    nameOverride:
    annotations:
      kubernetes.io/ingress.class: traefik-external
      #traefik.ingress.kubernetes.io/router.tls: "true"
      traefik.ingress.kubernetes.io/router.middlewares: traefik-chain-basic-auth@kubernetescrd
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    labels:
      app.kubernetes.io/name: zigbee2mqtt
    ingressClassName:  # "nginx"
    hosts:
      -  # -- Host address. Helm template can be passed.
        host: zigbee2mqtt.anotherlife.pl
        ## Configure the paths for the host
        paths:
          -  # -- Path.  Helm template can be passed.
            path: /
            pathType: Prefix
            service:
              name: zigbee2mqtt
              port: 8080
    tls:
    - hosts:
        - zigbee2mqtt.anotherlife.pl
      secretName: anotherlife-wildcard-certificate-staging   # -staging / -production


securityContext:
  # -- (bool) Privileged securityContext may be required if USB controller is accessed directly through the host machine
  privileged: true

  # -- Configure a hostPathMount to mount a USB device in the container.
persistence:
  config:
    enabled: true
    type: pvc
    mountPath: /data
    readOnly: false
    nameOverride:
    storageClass: "local-path"
    existingClaim:  # your-claim
    subPath:  # some-subpath
    accessMode: ReadWriteOnce
    size: 2Gi
    retain: false
  usb:
    enabled: true
    type: hostPath
    hostPath: /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 #/dev/serial/by-id/usb-1a86_USB_Serial-if00-port0 #/dev/ttyUSB0 

# -- Used in conjunction with `controller.type: statefulset` to create individual disks for each instance.
volumeClaimTemplates:
- name: data
  mountPath: /data
  accessMode: "ReadWriteOnce"
  size: 3Gi
  storageClass: "local-path"
# - name: backup
#   mountPath: /backup
#   subPath: theSubPath
#   accessMode: "ReadWriteOnce"
#   size: 2Gi
#   storageClass: "local-path"


nodeSelector:
  kubernetes.io/hostname: dev-k3s-master-2

# -- Affinity constraint rules to place the Pod on a specific node.
# [[ref]](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#affinity-and-anti-affinity)
affinity: {}
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zigbee-controller

# -- zigbee2mqtt configuration settings.
config:
  homeassistant: true
  permit_join: true
  mqtt:
    base_topic: zigbee2mqtt
    server: "mqtt://localhost"
    # user: my_user
    # password: my_password
    # client_id: my_id
    # password: '!secret password'

    # Optional: Include device information to mqtt messages (default: false)
    include_device_information: true

  # USB / Serial settings
  serial:
    port: /dev/ttyUSB0
    adapter: zstack
    disable_led: true

  advanced:
    network_key: GENERATE
    log_output:
      - console
    log_level: info

    # Optional: ZigBee channel, changing requires re-pairing of all devices. (Note: use a ZLL channel: 11, 15, 20, or 25 to avoid Problems)
    # default: 11
    # channel: 11

    # Optional: Baudrate for serial port (default: 115200 for Z-Stack, 38400 for Deconz)
    # baudrate: 38400

    # Optional: RTS / CTS Hardware Flow Control for serial port (default: false)
    # rtscts: true

    # Optional: Add a last_seen attribute to MQTT messages, contains date/time of last Zigbee message
    # possible values are: disable (default), ISO_8601, ISO_8601_local, epoch (default: disable)
    last_seen: 'ISO_8601'

    homeassistant_discovery_topic: 'homeassistant'
    homeassistant_status_topic: 'homeassistant/status'

    # Optional: Enables report feature (see information -> report for more details) (default: false)
    # report: true

    # Optional: Add an elapsed attribute to MQTT messages, contains milliseconds since the previous msg (default: false)
    # elapsed: true

  # Both of these need to be enabled for the webui
  frontend:
    port: 8080
  experimental:
    new_api: true




resources: {}
  ## We usually recommend not to specify default resources and to leave this as a conscious
  ## choice for the user. This also increases chances charts run on environments with little
  ## resources, such as Minikube. If you do want to specify resources, uncomment the following
  ## lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
