image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: 1.33.2

timezone: "UTC"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  runAsNonRoot: false
  privileged: true
service:
  port: 8080
  #type: ClusterIP

resources: {}

nodeSelector:
  kubernetes.io/hostname: dev-k3s-master-2

tolerations: []

affinity: {}

# affinity:
#   nodeAffinity:
#     requiredDuringSchedulingIgnoredDuringExecution:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: app
#           operator: In
#           values:
#           - zigbee-controller


# username: mqtt
# password: secret

persistence:
  storageClassName: local-path
  size: 2Gi


# usb:
#   enabled: true
#   type: hostPath
#   hostPath: '/dev/serial/by-path/pci-0000\:07\:1b.0-usb-0\:1\:1.0-port0' 

#device: /dev/ttyUSB0

# ingress:
#   enabled: true
#   ingressClassName: traefik
#   domainName: anotherlife.pl
#   secretName: cluster-tls


config:
  # These will be applied ONLY on first run
  homeassistant: true
  permit_join: true
  mqtt:
    base_topic: zigbee2mqtt
    server: 'mqtt://localhost'
    # user: my_user
    # password: my_password
    # Optional: Include device information to mqtt messages (default: false)
    include_device_information: true

  serial:
    port: /dev/serial/by-path/pci-0000\:07\:1b.0-usb-0\:1\:1.0-port0 #/dev/ttyUSB0
    adapter: zstack
    disable_led: true
  advanced:
    network_key: GENERATE
    log_output:
      - console