image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: 1.33.2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  runAsNonRoot: false

service:
  port: 8080

resources: {}

nodeSelector:
  kubernetes.io/hostname: k3s-node-0

tolerations: []

affinity: {}

username: mqtt
password: secret

persistence:
  storageClassName: local-path
  size: 2Gi

device: /dev/ttyUSB0

ingress:
  enabled: true
  ingressClassName: traefik
  domainName: anotherlife.pl
  secretName: cluster-tls


config:
  # These will be applied ONLY on first run
  # Home Assistant integration (MQTT discovery)
  homeassistant: false

  # allow new devices to join
  permit_join: true

  # MQTT settings
  mqtt:
    # MQTT base topic for zigbee2mqtt MQTT messages
    base_topic: zigbee2mqtt
    # MQTT server URL
    server: 'mqtt://localhost'
    # MQTT server authentication, uncomment if required:
    # user: my_user
    # password: my_password

  # Serial settings
  serial:
    # Location of CC2531 USB sniffer
    port: /dev/ttyUSB0

  advanced:
    network_key: GENERATE
    log_output:
      - console