image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: 1.33.2

timezone: "UTC"
imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  runAsNonRoot: false

service:
  port: 8080

resources: {}

# nodeSelector:
#   kubernetes.io/hostname: dev-k3s-master-2

tolerations: []

affinity: {}

# username: mqtt
# password: secret

persistence:
  storageClassName: local-path
  size: 2Gi

#device: /dev/ttyUSB0

# ingress:
#   enabled: true
#   ingressClassName: traefik
#   domainName: anotherlife.pl
#   secretName: cluster-tls


config:
  # These will be applied ONLY on first run
  homeassistant: true
  permit_join: true
  mqtt:
    base_topic: zigbee2mqtt
    server: 'mqtt://localhost'
    # user: my_user
    # password: my_password
  serial:
    # Location of CC2531 USB sniffer
    port: /dev/ttyUSB0
  advanced:
    network_key: GENERATE
    log_output:
      - console