image:
  repository: koenkk/zigbee2mqtt
  pullPolicy: IfNotPresent
  tag: 1.33.2

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  runAsNonRoot: false

service:
  port: 8080

resources: {}

nodeSelector:
  kubernetes.io/hostname: k3s-node-2

tolerations: []

affinity: {}

username: mqtt
password: secret

persistence:
  storageClassName: local-path
  size: 2Gi

device: /dev/ttyUSB0

# ingress:
#   enabled: true
#   ingressClassName: traefik
#   domainName: anotherlife.pl
#   secretName: cluster-tls
