apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "mktxp-exporter.fullname" . }}
  labels:
    {{- include "mktxp-exporter.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.persistence.storageClassName }}
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
