apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  name: {{ template "mosquitto.fullname" . }}
data:
  mosquitto.conf: |-
    {{- if .Values.persistence.enabled }}
    persistence true
    {{- else }}
    persistence false
    {{- end }}
    persistence_location /config/
    log_dest stdout
    log_type all
    password_file /config/accounts.conf
    acl_file /config/acls.conf
    listener {{ .Values.service.mqttPort }}

    {{- if .Values.mosquitto.ssl.enabled }}
    listener {{ .Values.service.mqttsslPort }}
    cafile /config/ssl/tls.crt
    certfile /config/ssl/tls.crt
    keyfile /config/ssl/tls.key
    {{- end }}


    {{- if .Values.mosquitto.allow_anonymous.enabled }}
    allow_anonymous true
    {{- end }}
    listener 1883
    listener 8883
    listener 9001
    #protocol websockets

{{ .Values.mosquitto.config | indent 4 }}
  accounts.conf: |-
{{ .Values.mosquitto.users | indent 4 }}
  acls.conf: |-
{{ .Values.mosquitto.acls | indent 4 }}
