apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
  name: {{ template "mosquitto.fullname" . }}
data:
  mosquitto.conf: |-
{{- if .Values.persistence.enabled }}
    persistence true
{{- else }}
    persistence false
{{- end }}
    persistence_location /mosquitto/config/
    persistence_file mosquitto.db
    log_dest stdout
    log_type all
    log_dest file /mosquitto/log/mosquitto.log
    pid_file /mosquitto/mosquitto.pid
    listener {{ .Values.service.mqttPort }}
    listener {{ .Values.service.mqttwsPort}}
    password_file /mosquitto/config/accounts.conf
{{- if .Values.mosquitto.ssl.enabled }}
    acl_file /mosquitto/config/acls.conf
    listener {{ .Values.service.mqttsslPort }}
    cafile /mosquitto/config/ssl/tls.crt
    certfile /mosquitto/config/ssl/tls.crt
    keyfile /mosquitto/config/ssl/tls.key
{{- end }}
{{- if .Values.mosquitto.allow_anonymous.enabled }}
    allow_anonymous true
{{- end }}
    protocol websockets
    autosave_interval 1800

{{ .Values.mosquitto.config | indent 4 }}
  accounts.conf: |-
    MQTT_PASSWORD
{{ .Values.mosquitto.users | indent 4 }}
  acls.conf: |-
{{ .Values.mosquitto.acls | indent 4 }}
