apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mosquitto.fullname" . }}
  labels:
    {{- include "mosquitto.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  revisionHistoryLimit:  {{ .Values.revisionHistoryLimit }}
  selector:
    matchLabels:
    {{- include "mosquitto.selectorLabels" . | nindent 6 }}
  strategy:
    type: {{ .Values.strategyType }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
      {{- include "mosquitto.selectorLabels" . | nindent 8 }}
      {{- if .Values.podLabels }}
      {{- toYaml .Values.podLabels | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.image.PullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automountServiceAccountToken }}
      shareProcessNamespace: {{ .Values.sidecarSingleProcessNamespace }}
      serviceAccountName: {{ include "mosquitto.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.securityContext | nindent 8 }}
      {{- if .Values.hostNetwork }}
      hostNetwork: {{ .Values.hostNetwork }}
      dnsPolicy: ClusterFirstWithHostNet
      {{- end }}

      initContainers:
      - name: setup-permissions
        image: busybox
        command: ["/bin/chown", "-R", "1883:1883", "/mosquitto"]
        securityContext:
          runAsUser: 0
          privileged: true
        volumeMounts:
        - name: datastorage
          mountPath: /mosquitto/data

      containers:
      - name: {{ .Chart.Name }}
        securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        args: [ "mosquitto", "-c", "/mosquitto/config/mosquitto.conf" ]
        env:
        {{- range $key, $value := .Values.extraEnv }}
        - name: {{ $key | }}
          value: {{ $value | }}
        {{- end }}
        {{- range $name, $opts := .Values.extraEnvSecrets }}
        - name: {{ $name }}
          valueFrom:
            secretKeyRef:
              name: {{ $opts.secret }}
              key: {{ $opts.key }}
        {{- end }}
        envFrom:
        {{- range .Values.extraSecretForEnvFrom }}
        - secretRef:
            name: {{ . }}
        {{- end }}
        resources:
        {{- toYaml .Values.resources | nindent 12 }}
        ports:
        - name: mqtt
          containerPort: {{ .Values.service.mqttPort }}
          protocol: TCP
        - name: mqttssl
          containerPort: {{ .Values.service.mqttsslPort }}
          protocol: TCP
        - name: mqttws
          containerPort: {{ .Values.service.mqttwsPort }}
          protocol: TCP
        - name: metrics
          containerPort: {{ .Values.service.metricsPort }}
          protocol: TCP

        {{- if .Values.livenessProbe.enabled }}
        livenessProbe:
          tcpSocket:
            port:              {{ .Values.service.mqttwsPort }}
          periodSeconds:       {{ .Values.livenessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds}}
        {{- end }}
        {{- if .Values.readinessProbe.enabled }}
        readinessProbe:
          tcpSocket:
            port:              {{ .Values.service.mqttwsPort }}
          periodSeconds:       {{ .Values.readinessProbe.periodSeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds}}
        {{- end }}

        volumeMounts:
        - name:      config
          mountPath: /mosquitto/config/mosquitto.conf
          subPath:   mosquitto.conf

        - name:      datastorage
          mountPath: /mosquitto/data

        {{- if .Values.mosquitto.ssl.enabled }}
        - name:      ssl-storage
          mountPath: /mosquitto/config/ssl
        {{- end }}

        {{- range .Values.hostMounts }}
        {{- if .mountPath }}
        - mountPath: {{ .mountPath }}
        {{- else }}
        - mountPath: {{ .hostPath }}
        {{- end }}
          name: {{ .name }}
        {{- end }}

      volumes:
      - name: config
        configMap:
          name: {{ include "mosquitto.fullname" . }}
          items:
          - key:  mosquitto.conf
            path: mosquitto.conf
            mode: 0640

      - name: datastorage
      {{- if .Values.persistence.enabled }}
      {{- if .Values.persistence.datastorage.hostPath }}
        hostPath:
          path: {{.Values.persistence.datastorage.hostPath}}
      {{- else }}
        persistentVolumeClaim:
          claimName: {{ if .Values.persistence.existingClaim }}{{ .Values.persistence.existingClaim }}{{- else }}{{ template "mosquitto.fullname" . }}{{- end }}
      {{- end }}

      {{- else }}
        emptyDir: {}
      {{ end }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
      {{- toYaml . | nindent 8 }}
      {{- end }}




{{/* 
      volumes:
        - name: config-volume
          configMap:
            name: {{ template "mosquitto.fullname" . }}

        # {{- if .Values.mosquitto.ssl.enabled }}
        # - name: ssl-volume
        #   secret:
        #     secretName: {{ .Values.mosquitto.ssl.secretName }}
        # {{- end }}

        {{- if not .Values.mosquitto.persistence.enabled }}
        - name: "mosquitto-data"
          emptyDir: {}
        {{- else }}

        - name: "mosquitto-data"
          persistentVolumeClaim:
        {{- if .Values.mosquitto.persistence.existingClaim }}
            claimName: {{ .Values.mosquitto.persistence.existingClaim }}
        {{- else }}
            claimName: {{ template "mosquitto.fullname" . }}
        {{- end }}
        {{- end }}
*/}}








      {{- range .Values.hostMounts }}
        - name: {{ .name }}
          hostPath:
            path: {{.hostPath}}
      {{- if .type }}
            type: {{ .type }}
      {{- end }}
      {{- end }}



