{{- if and .Values.persistence.pvc.enabled (not .Values.persistence.configstorage.hostPath) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include " mosquitto.fullname" . }}
  labels:
    {{- include " mosquitto.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.pvc.accessMode }}
  resources:
    requests:
      storage: {{ .Values.persistence.pvc.size }}
  {{- if .Values.persistence.pvc.storageClass }}
  storageClassName: "{{ .Values.persistence.pvc.storageClass }}"
  {{- end }}
{{- end }}