apiVersion: v1
kind: Service
metadata:
  {{- if .Values.service.annotations }}
  annotations:
  {{- toYaml .Values.service.annotations | nindent 4 }}
  {{- end }}
  name: {{ template "mosquitto.fullname" . }}
  labels:
  {{- include "mosquitto.labels" . | nindent 4 }}
  {{- if .Values.service.labels }}
  {{ toYaml .Values.service.labels | indent 4 }}
  {{- end }}

spec:
  type: {{ .Values.service.type }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
  {{- toYaml .Values.service.externalIPs | nindent 4 }}
  {{- end }}
  {{- if .Values.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy }}
  {{- end }}
  {{- if .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
  {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  publishNotReadyAddresses: {{ .Values.service.publishNotReadyAddresses }}
  ports:
  - name: mqtt
    port:  {{ .Values.service.mqttPort }}
    protocol: TCP
    targetPort: mqtt
  - name: mqttssl
    port: {{ .Values.service.mqttsslPort }}
    protocol: TCP
    targetPort: mqttssl
  - name: mqttws
    port: {{ .Values.service.mqttwsPort }}
    protocol: TCP
    targetPort: mqttws
  - name: metrics
    port: {{ .Values.service.metricsPort }}
    protocol: TCP
    targetPort: metrics
  selector:
  {{- include "mosquitto.selectorLabels" . | nindent 4 }}
