{{- if and .Values.ingress .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    helm.sh/chart: {{ include "app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  ingressClassName: {{ $.Values.ingress.ingressClassName }}
  rules:
    - host: {{ include "app.fullname" . }}.{{ $.Values.ingress.domainName }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "app.fullname" . }}
                port:
                  name: http
  tls:
    - secretName: {{ $.Values.ingress.secretName }}
      hosts:
        - {{ include "app.fullname" . }}.{{ $.Values.ingress.domainName }}
{{- end }}