{{- if and ( .Values.monitoring.serviceMonitor.enabled ) ( .Values.monitoring.enabled ) }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
{{- if .Values.monitoring.serviceMonitor.labels }}
  labels:
{{ toYaml .Values.monitoring.serviceMonitor.labels | indent 4}}
{{- end }}
  name: {{ template "app.fullname" . }}-prometheus-exporter
{{- if .Values.monitoring.serviceMonitor.namespace }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace }}
{{- end }}
spec:
  endpoints:
  - targetPort: {{ .Values.service.portName }}
    path: /api/prometheus
{{- if .Values.monitoring.serviceMonitor.interval }}
    interval: {{ .Values.monitoring.serviceMonitor.interval }}
{{- end }}


  jobLabel: {{ template "app.fullname" . }}-prometheus-exporter
  namespaceSelector:
    matchNames:
    - {{ .Release.Namespace }}
  selector:
    {{- include "app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/name: {{ include "app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
