apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
    # helm.sh/chart: {{ include "app.chart" . }}
    # app.kubernetes.io/instance: {{ .Release.Name }}
    # app.kubernetes.io/managed-by: {{ .Release.Service }}
    # app.kubernetes.io/name: {{ include "app.name" . }}

spec:
  replicas: 1
  podManagementPolicy: Parallel
  selector:
    matchLabels:
      {{- include "app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "app.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.securityContext | nindent 8 }}
      automountServiceAccountToken: false
      containers:
      - name: {{ .Chart.Name }}
        securityContext:
          {{- toYaml .Values.podSecurityContext | nindent 12 }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}

        # envFrom:
        # - configMapRef:
        #     name: {{ include "app.fullname" . }}-configurator

        ports:
        - name: http
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
        livenessProbe:
          httpGet:
            path:              /
            port:              {{ .Values.service.port }}
            scheme:            HTTP
          periodSeconds:       60
          timeoutSeconds:      10
          successThreshold:    1
          failureThreshold:    6
          initialDelaySeconds: 30
        readinessProbe:
          httpGet:
            path:              /
            port:              {{ .Values.service.port }}
            scheme:            HTTP
          periodSeconds:       60
          timeoutSeconds:      10
          successThreshold:    1
          failureThreshold:    2
          initialDelaySeconds: 30

        volumeMounts:
        - name: data
          mountPath: /config
        - name: localtime
          mountPath: /etc/localtime

      volumes:
      - name: data
        hostPath:
          path: {{ .Values.persistence.hostPath }}
      # - name: localtime
      #   hostPath:
      #     path: {{ .Values.persistence.hostPath: }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
