apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: home-assistant
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: home-assistant
    server: https://kubernetes.default.svc
  project: default #home-automation
  source:
    repoURL: 'https://jacekzubielik.github.io/helm-charts'
    targetRevision: 0.0.6
    chart: home-assistant
  
    helm:
      parameters:
        - name: installCRDs
          value: 'false'
      # valueFiles:
      #   - app-values.yaml
  syncPolicy:
    retry:
      limit: 2
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
      - preserveResourcesOnDeletion=false
      - Replace=false



