annotations:
  category: Application
apiVersion: v2
name: ha
description: Home Assistant chart
type: application
icon: https://raw.githubusercontent.com/home-assistant/assets/master/misc/logo-icon_template.png
version: 0.0.1
