---
image:
  repository: homeassistant/home-assistant
  pullPolicy: IfNotPresent
  tag: "2023.11.3"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  privileged: true

securityContext:
  runAsNonRoot: false

service:
  port: 8123

resources: {}

nodeSelector:
  #kubernetes.io/hostname: dev-k3s-master-0
  kubernetes.io/os: linux

tolerations: []

affinity: {}

persistence:
  storageClassName: local-path
  size: 2Gi

ingress:
  enabled: false
  ingressClassName: traefik
  domainName: anotherlife.pl
  secretName: letsencrypt-production
