image:
  repository: ghcr.io/akpw/mktxp
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podAnnotations: {}

podSecurityContext:
  runAsUser: 100
  runAsGroup: 101

securityContext:
  fsGroup: 101

service:
  port: 49090

resources: {}

nodeSelector:
  kubernetes.io/hostname: {}

tolerations: []

affinity: {}

persistence:
  storageClassName: local-path
  size: 1Gi

# ingress:
#   enabled: false
#   ingressClassName: traefik
#   domainName: {}
#   secretName: cluster-tls

monitoring:
  enabled: true
  serviceMonitor:
    enabled: true
    interval: 60s
    labels:
      prometheus: "true"
